# Generated by Django 3.2.4 on 2021-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_questionmodel_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question_image',
            field=models.ImageField(blank=True, upload_to='quiz_images'),
        ),
    ]
