# Generated by Django 3.2.4 on 2021-06-22 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('num_sold', models.IntegerField(blank=True, default=0)),
                ('quantity_available', models.PositiveIntegerField(default=100)),
            ],
        ),
    ]
